language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
- osx
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install git libjsoncpp-dev libssl-dev; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install git openssl jsoncpp; fi
before_script:
- git submodule update --init --recursive
- mkdir build
- cd build
- if [ $TRAVIS_OS_NAME == osx ]; then cmake -Wno-dev -DWITH_TESTS=ON -DBUILD_SHARED_LIBS=ON -DOPENSSL_ROOT_DIR=$(brew --prefix openssl) -DCMAKE_INSTALL_PREFIX=/usr/local ..; fi
- if [ $TRAVIS_OS_NAME == linux ]; then cmake -DWITH_TESTS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/local ..; fi
script:
- make
- ./jwtpp_test
- sudo make install
branches:
  only:
  - master
  - "/^v\\d+\\./"
